services:
    traefik:
        image: traefik:v3.6.13
        container_name: traefik
        restart: unless-stopped
        ports:
            - '80:80'
            - "443:443/tcp"
            - "443:443/udp"
            - '8080:8080'
        command:
            - '--providers.docker=true'
            - '--providers.docker.exposedbydefault=false'
            - '--entrypoints.web.address=:80'
            - '--entrypoints.websecure.address=:443'

            # Enable dashboard
            - '--api.dashboard=true'
            - '--api.insecure=true'

            # Enable http/3
            - "--entrypoints.websecure.http3=true"

            # Experimental FastProxy
            - "--experimental.fastProxy"

            # 🐞 Info logs
            - '--log.level=INFO'

            # 🔁 Global redirect
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

            # --- Add these lines for Let's Encrypt ---
            - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

            # Disable timeout
            - '--entrypoints.websecure.transport.respondingTimeouts.readTimeout=0'
            - '--entrypoints.websecure.transport.respondingTimeouts.idleTimeout=0'

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - letsencrypt:/letsencrypt
        networks:
            - proxy

volumes:
    letsencrypt:


networks:
    proxy:
        external: true
