services:
  landing:
    image: ghcr.io/chithi-dev/chithi-landing-page:latest
    container_name: landing
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=Host(`landing.chithi.dev`)"
      - "traefik.http.routers.landing.entrypoints=websecure"
      - "traefik.http.routers.landing.tls=true"
      - "traefik.http.routers.landing.tls.certresolver=letsencrypt"
      - "traefik.http.services.landing.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
