services:
  deluge:
    image: linuxserver/deluge:2.2.0-libtorrentv1
    user: 1000:1000
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    ports:
      - '6881:6881'
      - '6881:6881/udp'
    volumes:
      - deluge_config:/config
      - /mnt/toshiba:/downloads/toshiba
      - /mnt/hitachi:/downloads/hitachi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.rule=Host(`deluge.homelab.zad.bd`)"
      - "traefik.http.routers.deluge.entrypoints=websecure"
      - "traefik.http.routers.deluge.tls=true"
      - "traefik.http.routers.deluge.tls.certresolver=letsencrypt"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
      - "traefik.http.services.deluge.loadbalancer.server.scheme=http"
    networks:
      - proxy
    depends_on:
      volume-permission-helper:
        condition: service_completed_successfully

  volume-permission-helper:
      image: alpine
      volumes:
        - deluge_config:/config
      command: >
        sh -c "
          chown -R 1000:1000 /config &&
          echo 'Volume Permissions fixed' &&
          exit 0
        "
      restart: "no"
      
volumes:
  deluge_config:

networks:
  proxy:
    external: true
