services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped

    environment:
      - BASE_URL=https://searxng.homelab.zad.bd
      - INSTANCE_NAME=Homelab SearXNG

      # Redis (used by SearXNG)
      - SEARXNG_REDIS_URL=redis://redis:6379/0

      # Optional DB (only useful if your config uses it)
      - SEARXNG_DB_URL=postgresql://searxng:searxng_pass@postgres:5432/searxng

    volumes:
      - ./searxng.yml:/etc/searxng/settings.yml
      - searxng_config:/etc/searxng

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - proxy
      - backend

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.searxng.rule=Host(`searxng.homelab.zad.bd`)"
      - "traefik.http.routers.searxng.entrypoints=websecure"
      - "traefik.http.routers.searxng.tls.certresolver=letsencrypt"

      - "traefik.http.services.searxng.loadbalancer.server.port=8080"

      # forwarded headers
      - "traefik.http.middlewares.searxng-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.searxng-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.routers.searxng.middlewares=searxng-headers"


  postgres:
    image: postgres:18-alpine
    container_name: searxng-postgres
    restart: unless-stopped

    environment:
      - POSTGRES_DB=searxng
      - POSTGRES_USER=searxng
      - POSTGRES_PASSWORD=searxng_pass

    volumes:
      - postgres_data:/var/lib/postgresql
      
    networks:
      - backend

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U searxng -d searxng"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  proxy:
    external: true

  backend:
    driver: bridge

volumes:
  searxng_config:
  redis_data:
  postgres_data:
