services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    depends_on:
      - postgres

    environment:
      - BASE_URL=https://searxng.homelab.zad.bd
      - INSTANCE_NAME=Homelab SearXNG

    volumes:
      - ./searxng.yml:/etc/searxng/settings.yml
      - searxng_config:/etc/searxng
    labels:
      - "traefik.enable=true"

      # HTTPS router
      - "traefik.http.routers.searxng.rule=Host(`searxng.homelab.zad.bd`)"
      - "traefik.http.routers.searxng.entrypoints=websecure"
      - "traefik.http.routers.searxng.tls.certresolver=letsencrypt"

      # internal port
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"

      #  forwarded headers middleware
      - "traefik.http.middlewares.searxng-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.searxng-headers.headers.customrequestheaders.X-Forwarded-Port=443"

      - "traefik.http.routers.searxng.middlewares=searxng-headers"
    networks:
      - proxy
      - db
      
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
  postgres:
    image: postgres:16-alpine
    container_name: searxng_postgres
    restart: unless-stopped

    environment:
      - POSTGRES_USER=searxng
      - POSTGRES_PASSWORD=searxng_password
      - POSTGRES_DB=searxng

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - db

    

networks:
  proxy:
    external: true
  db:

volumes:
  searxng_config:
  postgres_data: