version: "3.9"

services:
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    restart: unless-stopped
    command: >
      server
      -dir=/data
      -s3
      -ip=seaweedfs
    ports:
      - "9333:9333"   # master
      - "8080:8080"   # volume
      - "8333:8333"   # S3 API
    volumes:
      - seaweed_data:/data

volumes:
  seaweed_data:
