
services:
  master:
    image: chrislusf/seaweedfs:latest
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master -volumeSizeLimitMB=100"
  volume:
    image: chrislusf/seaweedfs:latest
    ports:
      - 8080:8080
      - 18080:18080
    command: "volume -master=master:9333 -port=8080 -ip=volume -max=0 -preStopSeconds=1"
    depends_on:
      - master
  s3:
    image: chrislusf/seaweedfs:latest 
    ports:
      - 8888:8888
      - 18888:18888
      - 8333:8333
    command: '-v 9 filer -master="master:9333" -s3 -s3.config=/etc/seaweedfs/s3.json -s3.port=8333'
    volumes:
      - ./s3.json:/etc/seaweedfs/s3.json
    depends_on:
      - master
      - volume